### ISSUE TITLE
Mable module test does not produce deterministic results when a single test is re-run in debug

### ISSUE THREAD

**Issue by lausdahl** [INTO-CPS-Association/maestro#102]
The class FullSpecTest(PrettyPrint) can be run once to produce a list of test cases in IntelliJ but if a single of these is selected and run is chosen then intellij may run a different test. There must be a misconfiguration somewhere because this works in maestro 1 and Overture.

**Comment by CThuleHansen** [comment]
test

Casper Thule
Postdoc at Centre for Digital Twins
Mail: casper.thule@eng.au.dk<mailto:casper.thule@eng.au.dk>
Aarhus University, Department of Engineering | Åbogade 34 (Turing building), room 122 | DK - 8200 Aarhus N
