### ISSUE TITLE
interpreter equality not implemented for null values

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#125]
`org.intocps.maestro.interpreter.InterpreterException: Equality not implement for: FmuValue == NullValue (org.intocps.maestro.interpreter.values.fmi.FmuValue@47311277 == null)`

Whoever fixes it first...

**Comment by lausdahl** [comment]
:-) that was fixed but you took it out. That was the reason why the throw was commented. So assume you want dedicated handling of that case then

**Comment by CThuleHansen** [comment]
yes I understand that now hehe

**Comment by CThuleHansen** [comment]
I am just wondering if it is correct to have default false. It might hide a lot of other issues similar to the boolean one? How would we detect that?

**Comment by lausdahl** [comment]
We should probably have explicit handling since the reason for this issue is that it implicitly declared a true comparison false.

**Comment by lausdahl** [comment]
Added explicit null equals in 90ea85db50971e525c841de4766f1945a3f1c734 but also removed duble evaluation of numbers and booleans
