### ISSUE TITLE
Mimic maestro 1.x.x CLI

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#135]
The cli to maestro2 should be the same as for maestro 1.x.x

**Comment by lausdahl** [comment]
This should be added in 8704c7381a9fee313acb74ffc126c750f5e60541 but without the exit codes

**Comment by lausdahl** [comment]
Added exit 1 in 54de72844b7e59ea66430b6152d0bdf6ed025a32
