### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#143]
New CLI according to ideas in https://into-cps-maestro.readthedocs.io/en/latest/user/getting-started.html with other flags
-sg1 for legacy configuration files.

**Comment by lausdahl** [comment]
Added in 722b0517082304ca9fbb4244ad6df83a2855f2b2 but slidely different.

The cli now has `-sg1` or `--spec-generate1` to take the old initialize and simulation files. These should just be given as the additional arguments at the end. They need to have the extension `.json`. All files named `.mabl` will alway be parsed.

`-d` sets the dump path I this is probably the same as output or build dir
