### ISSUE TITLE
Maestro V2 problem with Three Tank 

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/maestro#156]
15:09:05.420 [http-nio-8082-exec-6] DEBUG org.intocps.fmi.jnifmuapi.NativeLibraryLoader - Extracting library from: lib/Linux-amd64/libfmuapi.so
15:09:05.443 [http-nio-8082-exec-6] DEBUG org.intocps.fmi.jnifmuapi.NativeLibraryLoader - Extracted library: /tmp/jnifmuapi10158058749612071915/jnifmuapi-Linux-amd64/libfmuapi.so
15:09:05.445 [http-nio-8082-exec-6] DEBUG org.intocps.fmi.jnifmuapi.NativeFmu - Loaded Library file: /tmp/jnifmuapi10158058749612071915/jnifmuapi-Linux-amd64/libfmuapi.so
ast-tc.mappings line 7: No such constructor: TCOnFailAnnotation(LexIdentifierToken, ASTExpressionList)

Fields available from ASTOnFailAnnotation:
    LexIdentifierToken name
    ASTExpressionList args
Constructors available for TCOnFailAnnotation:
    TCOnFailAnnotation(TCIdentifierToken, TCExpressionList)

Aborting with 1 errors

**Comment by CThuleHansen** [comment]
Which version of Maestro?

**Comment by CThuleHansen** [comment]
It is related to this: https://github.com/nickbattle/vdmj/pull/38

**Comment by CThuleHansen** [comment]
Closing this issue, as it is related to a issue in an older release.
