### ISSUE TITLE
Logging in oneshot mode

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/maestro#16]
The "one shot" mode is useful for scripting but the functionality differs from online mode in that:
 
- The log is not returned returned / saved. 
- overrideLogLevel seems to be ignored.

It would be useful if the functionality here was aligned.

**Comment by kgpierce** [comment]
Actually it looks like the App is doing something extra with the log, will try to replicate and close this if needed.

**Comment by kgpierce** [comment]
When simulating in online mode and selecting "enable all log categories per instance" the following (example) is sent by the App to the simulate command:

{"startTime":0,"endTime":3,"reportProgress":true,"liveLogInterval":0,"logLevels":{"{G}.GInstance":["logAll","logError","logFmiCall","Protocol","VdmErr","VdmOut"],"{H}.HInstance":["logAll","logError","logFmiCall","Protocol","VdmErr","VdmOut"]}}

The oneshot simulation creates an empty map:

https://github.com/INTO-CPS-Association/maestro/blob/f5c877c3c7740dffc5e6c811f4fccb5f0bfb97b5/orchestration/coe/src/main/java/org/intocps/orchestration/coe/util/SimulationExecutionUtil.java#L220

So these options aren't available in oneshot mode.

**Comment by kgpierce** [comment]
One thought is to replace -e,--endtime <time>/ -e,--endtime <time> with a --simulation_config JSON as is done in online mode? Would be good if config and this could take them as a string or filename.

**Comment by kgpierce** [comment]
Perhaps, regarding my second bullet, --result could be a path where CSV and any logs are saved? In addition, being able to pipe them back someone so save writing to disk might be useful (not sure the best mechanism for this).

**Comment by CThuleHansen** [comment]
The COE with support for this is available i.e. here: 
https://github.com/INTO-CPS-Association/maestro/actions/runs/193192484 
and in subsequent builds.
