### ISSUE TITLE
Logging granularity 

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/maestro#17]
It would be useful to have finer-grained control over logging, for example by turning logging on with a specific log level for a single FMU, or different log levels for different FMUs. My main use case is that VDM console appears as [DEBUG] and to turn this on I have to globally override which slows things down.

**Comment by CThuleHansen** [comment]
@kgpierce I am happy to say, that @lausdahl has addressed this in the alpha of maestro2
