### ISSUE TITLE
Value inheritance?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#192]
I cannot really figure out the way to go with inheritance, so here is a writeup:

DoubleValue can originate from two places: 
1. Within a DoubleVariable (`DoubleVariableFmi2Api extends VariableFmi2Api<Fmi2Builder.DoubleValue>`
2. The introduction of a double into the api, i.e. `DoubleValue five = of(5.0)`
A DoubleValue is a numeric, so: DoubleValue extends NumericValue.
Thus, we get the following inheritance: `DoubleValue extends NumericValue` and `NumericValue extends Value.`

Thus, we have two different doublevalues: Primitive ones (`of(5.0)`) and the ones that refer to an identifier (`DoubleVariable`).
The have the similarity that their type is the same, yet they have the difference in expression.
Should we have different classes for the two? I.e. `PrimitiveDoubleValue extends DoubleValue`?

A NumericValue contains functions to perform math but also functions to perform i.e. `<` with other NumericValues, in which case it returns a predicate.

**Comment by nickbattle** [comment]
I see you've closed this again, so perhaps you've clarified the situation?

I'd need more background to compare to what VDMJ does, but it sounds like you're either confusing a variable expression with a variable value, or you're confusing L-values and R-values. Generally, I would say keeping these things distinct is the way to go. That is, a variable expression just represents a grammatical expression in the AST, but does not have a "value" as such; the evaluation of a variable expression within a *runtime* context that binds names to pure values would result in a pure value. L-values are variable expressions that refer to values (by name) that can be updated; R-values are expressions that can be evaluated but which don't change the variables concerned. Does that help?
