### ISSUE TITLE
Error in co-simulation

### ISSUE THREAD

**Issue by JensJakobMikkelsen** [INTO-CPS-Association/maestro#24]
![billede](https://user-images.githubusercontent.com/17762276/75349129-70e29600-58a4-11ea-91a7-7bf873006209.png)

Problem occuring in COE 1.0.4, java build 1.8.0_221-b11, Windows 10.

**Comment by CThuleHansen** [comment]
Thank you. Will investigate.

**Comment by CThuleHansen** [comment]
It should be an error, just not fatal.
