### ISSUE TITLE
Aggregate the results of external tests

### ISSUE THREAD

**Issue by FrederikPM** [INTO-CPS-Association/maestro#243]
As of now running all external tests just runs the individual test scripts one after another.
It woul be nice to accumulate the results and display them in a clear concise manner at the end.

**Comment by CThuleHansen** [comment]
On github actions it should be separated. 
Locally, it would be fine to run all three with one command, i.e. a python script wrapping the other ones.

On github actions we need to mark it as failed when faield. I.e. if CSV files do not match, then fail it.
This can probably be done by sys.exit(1)

**Comment by FrederikPM** [comment]
This should also include changing from using a requirements.txt to a Pipfile.
