### ISSUE TITLE
JacobianStepBuilder reads config from string parameter

### ISSUE THREAD

**Issue by lausdahl** [INTO-CPS-Association/maestro#261]
A plugin should not read a system file using a string parameter. If a config is required then it must be passed as a config annotation. See `variableStepConfig` if more data is required it must be assembled into one file as send in through config

**Comment by CThuleHansen** [comment]
I do not understand this - can you elaborate?

**Comment by CThuleHansen** [comment]
Here is an example: https://github.com/INTO-CPS-Association/maestro/blob/development/maestro/src/test/resources/specifications/full/initialize_jacobianstepbuilder_unfold_loop/jacobian_single_wt.mabl#L31-L32

**Comment by FrederikPM** [comment]
Depends on #276
