### ISSUE TITLE
Type is not correct!

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#282]
https://github.com/INTO-CPS-Association/maestro/blob/9d16f56e8c45538b13ce12e78f743085fdfbd302/frameworks/fmi2api/src/main/java/org/intocps/maestro/framework/fmi2/api/mabl/variables/ComponentVariableFmi2Api.java#L742

Gives an error when the selectedPorts are of a different type.
In the image below, a string has been retrieved. But it is trying to store it in an intermediate real array (valbuf.type), before setting it.
![image](https://user-images.githubusercontent.com/3479481/123806256-0b1a7a00-d8ef-11eb-9eec-182fed7dd88b.png)

It is necessary to filter the ports on the type in this function.

**Comment by FrederikPM** [comment]
Would grouping the ports by type and iterating over each resulting grouping with the logic from line 743 to 756 solve this:

 sortedPorts.stream().collect(Collectors.groupingBy(PortFmi2Api::getType)).forEach((key, value) -> {
            ArrayVariableFmi2Api<Object> valBuf = getIOBuffer(key);
            for (int i = 0; i < value.size(); i++) {
                PortFmi2Api p = value.get(i);
                PStateDesignator designator = valBuf.items().get(i).getDesignator();


                scope.addAll(BuilderUtil.createTypeConvertingAssignment(builder, scope, designator.clone(), portToValue.apply(p).getKey().clone(),
                        portToValue.apply(p).getValue(), valBuf.type));
            }

            AAssigmentStm stm = newAAssignmentStm(((IMablScope) scope).getFmiStatusVariable().getDesignator().clone(),
                    call(this.getReferenceExp().clone(), createFunctionName(FmiFunctionType.SET, value.get(0)),
                            vrefBuf.getReferenceExp().clone(), newAUIntLiteralExp((long) value.size()), valBuf.getReferenceExp().clone()));
            scope.add(stm);

            if (builder.getSettings().fmiErrorHandlingEnabled) {
                FmiStatusErrorHandlingBuilder.generate(builder, createFunctionName(FmiFunctionType.SET, value.get(0)), this, (IMablScope) scope,
                        MablApiBuilder.FmiStatus.FMI_ERROR, MablApiBuilder.FmiStatus.FMI_FATAL);
            }
        });

Is there something to test this with?

**Comment by CThuleHansen** [comment]
Cannot get the full picture as I am phone, but the idea is correct. The rbmqtest in fault injection maestro repo of into-cps association throws a type checker exception currently because of it.

**Comment by CThuleHansen** [comment]
Is this fixed? @FrederikPM

**Comment by FrederikPM** [comment]
Yes this should be fixed on development.
