### ISSUE TITLE
CLI test sometimes fails on Windows

### ISSUE THREAD

**Issue by FrederikPM** [INTO-CPS-Association/maestro#321]
For some actions the CLI test fails at _CLI export cpp_ and only on Windows:
https://github.com/INTO-CPS-Association/maestro/runs/3368711367?check_suite_focus=true
https://github.com/INTO-CPS-Association/maestro/runs/3193499319?check_suite_focus=true
https://github.com/INTO-CPS-Association/maestro/runs/3359884672?check_suite_focus=true
The error seems to be: "mingw32-make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/sim.dir/all] Error 130".
@lausdahl are you able to look into this?

**Comment by CThuleHansen** [comment]
This was due to the github action having a too short time out
