### ISSUE TITLE
Scenario-Verifier renaming

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#323]
Scenario-Verifier is VERY general. Perhaps some sort of name? I.e. @clagms choose MOBSTER to identify a specific approach of Model Based Tester (and he went even further, he made FMIMOBSTER). 

This makes it unique. @SimplisticCode / @clagms  any ideas to makes it a tad more unique?

**Comment by clagms** [comment]
@SimplisticCode I'll leave it to you to have fun finding a name.
For the FMIMOBSTER I used one of the acronym generation tools:
https://www.google.com/search?q=acronym+generator

Add some relevant keywords of what the tool does "Like co-simulation scenario verifier" or "orchestration algorithm generator". and try to find a nice acronym.

**Comment by FrederikPM** [comment]
It has been renamed to SIGVER
