### ISSUE TITLE
Make it possible to retrieve specification even if execution failed.

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#344]
Adapt the web api such that this is possible.
see https://github.com/INTO-CPS-Association/into-cps-application/issues/165

**Comment by CThuleHansen** [comment]
I think you are completely correct. 
My bad :)

**Comment by FrederikPM** [comment]
Okay. I will close this issue when the accompanying issue has been closed.

**Comment by CThuleHansen** [comment]
What is the accompanying issue? If you cannot remember (I cannot), then just close the issue, and it can be reopened if needed.

**Comment by FrederikPM** [comment]
The accompanying issue is in the [Into-cps-application repo](https://github.com/INTO-CPS-Association/into-cps-application/issues/165), I should probably have linked to it before.
However, I think that we can safely conclude that only changes to the app is needed and therefore close this issue.
