### ISSUE TITLE
Outputs are not extracted for fmus wrapped with the fault injection plugin

### ISSUE THREAD

**Issue by gitting-around** [INTO-CPS-Association/maestro#350]

**Comment by gitting-around** [comment]
For this multimodel:
[multiModel.txt](https://github.com/INTO-CPS-Association/maestro/files/7482278/multiModel.txt)
the following mabl spec is generated:
[spec.txt](https://github.com/INTO-CPS-Association/maestro/files/7482282/spec.txt)

**Comment by CThuleHansen** [comment]
I hope this is fixed in https://github.com/INTO-CPS-Association/maestro/pull/351

**Comment by CThuleHansen** [comment]
Closing. Repon if necessary
