### ISSUE TITLE
Missing dependency in Windows-amd64\fmuapi.dll

### ISSUE THREAD

**Issue by IntLucas** [INTO-CPS-Association/maestro#415]
`maestro.jar\lib\Windows-amd64\fmuapi.dll` has missing library `libwinpthread-1.dll`, from Mingw I suspect.

**Comment by lausdahl** [comment]
Yes that is a mingw dependency that should not be there. This should be fixed by https://github.com/INTO-CPS-Association/maestro/pull/419 as of next release >2.4.0
