### ISSUE TITLE
Windows 32-bit/64-bit interoperability

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#5]
A 64-bit process cannot load a 32-bit dll and a 32-bit process cannot load a 64-bit dll.
However, when attempting to load a 32-bit dll using a 64-bit JRE, the error message is imprecise and unclear:
```
 ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:295) - Internal error in initialization 
{Identity} library does not exist: C:\Users\clagms\AppData\Local\Temp\Identity6465429152427439231\binaries\win64\Identity.dll 
{Delay} library does not exist: C:\Users\clagms\AppData\Local\Temp\Delay8977716373425555182\binaries\win64\Delay.dll 
org.intocps.orchestration.coe.AbortSimulationException: An FMU library didn't load 
at org.intocps.orchestration.coe.scala.CoeInitialize$.initialize(CoeInitialize.scala:76) 
{StateMachine} library does not exist: C:\Users\clagms\AppData\Local\Temp\StateMachine5081232574623317570\binaries\win64\StateMachine.dll 
```

A check should be implemented that tests whether the FMU matches the JRE and issue a better error message, in case these do not correspond.

**Comment by lausdahl** [comment]
If you take a look at https://github.com/INTO-CPS-Association/org.intocps.maestro.fmi/blob/development/jnifmuapi/src/main/java/org/intocps/fmi/jnifmuapi/DirectoryFmu.java#L126-L132 then its clear that the Java code cannot do much. It calculated the correct plantform name and loads it. The above error must thus be when an FMU is wrongly packed placing a library in the FMU with the wrong OS extension. This is not easy to detect. It will probably require to call some underlying OS function like `file` in unix to check the type of library (it will slow down execution for all the ones packed correctly)

**Comment by CThuleHansen** [comment]
Thank you for looking into it!
