### ISSUE TITLE
TypeConverter does not cover all possible conversions

### ISSUE THREAD

**Issue by SimplisticCode** [INTO-CPS-Association/maestro#59]
The conversions should cover the following scenarios:
Real <-> Int
Int <-> Boolean
Real <-> Boolean

**Comment by CThuleHansen** [comment]
@clagms do you have any sources on how the conversions above should be carried out for co-simulation in general?

**Comment by clagms** [comment]
For any conversion, it's hard to tell:
- whether it's an error in the config of the co-simulation scenario (maybe the user specified the wrong connection)?
- What the conversion should be...
- Whether we should abort or just warn the user that a conversion happened...

I don't know whether we should prioritize convenience or safety... I'd say that we should go for safety and probably not allow any conversion to happen.
If the user really wants to convert something, then he/she has to explicitly specify it. Then we can apply some casting.

Something like:
- Real -> Int is floor
- True is 1, and False is 0
- 0 is false, anything else is true (is this reasonable?)
- True is 1.0 and False is 0.0
- 0.0 is false, anything else is True.

**Comment by nickbattle** [comment]
I'm not really sure of the ramifications here, but one aspect that may be important is whether there is information loss in the conversion. So for example, a real converted to an integer is lossy and should perhaps be an error (unless the user adds an explicit cast, in which case we floor or round or whatever). On the other hand, int to real or int to boolean are not lossy as such, and perhaps only warrant a warning. After a cast is added, we shift the blame and responsibility to the user and so give no warnings or errors.

Another thought: these are type conversions between FMU inputs/outputs? So are we dealing with symbolic types, like "voltage" or "torque", or are we dealing with raw data types like int/real/boolean? Perhaps FMUs from different sources could not be expected to have the same type names anyway, but it might be a "higher level" at which to describe the conversion?

So the output of an FMU might be type "Acceleration(real)", and that could be accepted by another FMU with an input of the same type. Or it may mean that Maestro would have to add a layer of its own type names over the FMU's configuration. But this would be an explicit way to "see" the meaning of the types in a model - so you might have a description that says that "output Acc(Acceleration)" connects to "input DeltaV(Acceleration)", meaning that Acc and DeltaV are the same type, called "Acceleration", which for this combination of FMUs Maestro defines as Acceleration=real. A cast/warning/error would then occur if (say) DeltaV was actually an integer.

**Comment by clagms** [comment]
Completely agree with the warnings and errors on the lossy conversions in general.

>Another thought: these are type conversions between FMU inputs/outputs? So are we dealing with symbolic types, like "voltage" or "torque", or are we dealing with raw data types like int/real/boolean? Perhaps FMUs from different sources could not be expected to have the same type names anyway, but it might be a "higher level" at which to describe the conversion?

I assume this is the case. So I would not allow any implicit conversion at all, to prevent modelling errors and then hard to debug problems in the simulation (just imagine a simulation where one real input is being cast into a integer.. causing only slightly deviations on the simulation results... and everybody assumes they make sense.)
Ideally, we would look at the units of each connected ports and make sure they match and give an error if they don't.. Doing automatic conversions is too fancy to be in our scope (imho).

**Comment by nickbattle** [comment]
Ah yes, of course we may have units as well as type names. So output-to-input connections can be checked for compatibility and (if not identical) the modeller can define (what?) multipliers to do unit conversion as well as acceptable casts to another raw type?

Given that FMI units are represented in common SI unit terms, is automatic conversion that difficult? (Haven't thought about it very hard!)

**Comment by clagms** [comment]
> Given that FMI units are represented in common SI unit terms, is automatic conversion that difficult? (Haven't thought about it very hard!)

This is what's writen in the fmi standard doc.
A quick google search shows that it seems possible to do automatically, but hard to tell whether it's simple:
- https://www.cs.utexas.edu/users/novak/units95.html
- http://www.mathframe.com/articles/usef/physical_units/index.html

I haven't checked, but I doubt the above involve reference frame transformations as well (e.g., position are automatically converted, but the origin of these positions is incorrect).
So users who connect FMUs together must be well aware of what the units involved are, and the reference frames. If they don't, and we provide a tool to help them, we might be doing more harm than good. If they know what they are doing, unit conversion won't be hard for them (and our work will be provide a marginal improvement).
