### ISSUE TITLE
Initialisation of systems containing algebraic loops

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#9]
How should systems containing algebraic loops be initialised? 
By starting somewhere and just keep going until the outputs changes are lower than a certain threshold?

**Comment by hyumo** [comment]
It does not always converge from my experience. It might be more reliable using newtons method, however, it only works for algebraic loops without any integer type connectors. 

I am searching for help with integer connectors in the loop, and then I found this post.

**Comment by CThuleHansen** [comment]
Hi @hyumo , thank you for commenting, I will take it into consideration and try to figure out what additional configuration to include.
 
FYI: We have a tutorial on continuous time co-simulation coming up, will probably be published on arxiv tomorrow.

**Comment by hyumo** [comment]
https://arxiv.org/abs/1809.08463

This is awesome

**Comment by CThuleHansen** [comment]
Great you found it!

**Comment by CThuleHansen** [comment]
Closing until needed
